import type { StbConfig, BaseStyleElementDef, BaseStylesSpacingPadding, BaseStylesSpacing } from '../types.js';
import { camelToKebab } from '../types.js';
import { resolveForScss, ensureFontStyle } from '../config.js';

/** Property output order for consistent generated CSS */
const PROPERTY_ORDER = ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'lineHeight'] as const;

/** Padding sides in output order */
const PADDING_SIDES = ['top', 'right', 'bottom', 'left'] as const;

export function generateContentScss(config: StbConfig): string | null {
  if (!config.baseStyles) return null;

  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
  ];

  const { baseStyles, prefix, tokens } = config;
  const hasBodyTypography = !!baseStyles.body;
  const hasSpacingPadding = !!baseStyles.spacing?.padding;
  const hasBlockGap = !!baseStyles.spacing?.blockGap;

  // Body — wraps in body { } for typography, root padding variables, and/or block gap
  if (hasBodyTypography || hasSpacingPadding || hasBlockGap) {
    lines.push('body {');

    // Typography declarations
    if (baseStyles.body) {
      appendDeclarations(lines, baseStyles.body, prefix, tokens, '  ');
    }

    // Root padding CSS custom properties
    if (baseStyles.spacing?.padding) {
      appendRootPaddingVars(lines, baseStyles.spacing.padding, prefix, tokens);
    }

    // Block gap CSS custom property
    if (baseStyles.spacing?.blockGap) {
      appendBlockGapVar(lines, baseStyles.spacing, prefix, tokens);
    }

    lines.push('}');
  }

  // Block gap layout utility rules
  if (hasBlockGap) {
    appendBlockGapRules(lines, prefix);
  }

  // Global padding + alignfull rules
  if (hasSpacingPadding) {
    lines.push('');
    lines.push('.has-global-padding {');
    lines.push(`  padding-right: var(--${prefix}--root-padding-right);`);
    lines.push(`  padding-left: var(--${prefix}--root-padding-left);`);
    lines.push('}');

    lines.push('');
    lines.push('.has-global-padding > .alignfull {');
    lines.push('  max-width: none;');
    lines.push(`  margin-right: calc(var(--${prefix}--root-padding-right) * -1);`);
    lines.push(`  margin-left: calc(var(--${prefix}--root-padding-left) * -1);`);
    lines.push('}');

    lines.push('');
    lines.push('.has-global-padding > .alignfull > .has-global-padding {');
    lines.push(`  padding-right: var(--${prefix}--root-padding-right);`);
    lines.push(`  padding-left: var(--${prefix}--root-padding-left);`);
    lines.push('}');
  }

  // Heading group — :where(h1, h2, h3, h4, h5, h6) { ... }
  if (baseStyles.heading) {
    lines.push('');
    lines.push(':where(h1, h2, h3, h4, h5, h6) {');
    appendDeclarations(lines, baseStyles.heading, prefix, tokens, '  ');
    lines.push('}');
  }

  // Individual headings — :where(hN) { ... }
  const headingLevels = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] as const;
  for (const level of headingLevels) {
    const def = baseStyles[level];
    if (!def) continue;
    lines.push('');
    lines.push(`:where(${level}) {`);
    appendDeclarations(lines, ensureFontStyle(def), prefix, tokens, '  ');
    lines.push('}');
  }

  // Caption — :where(figcaption) { ... }
  if (baseStyles.caption) {
    lines.push('');
    lines.push(':where(figcaption) {');
    appendDeclarations(lines, baseStyles.caption, prefix, tokens, '  ');
    lines.push('}');
  }

  // Button — :where(button) { ... }
  if (baseStyles.button) {
    lines.push('');
    lines.push(':where(button) {');
    appendDeclarations(lines, baseStyles.button, prefix, tokens, '  ');
    lines.push('}');
  }

  // Link — :where(a) { ... } and :where(a:hover) { ... }
  if (baseStyles.link) {
    lines.push('');
    lines.push(':where(a) {');
    appendDeclarations(lines, baseStyles.link, prefix, tokens, '  ');
    lines.push('}');

    if (baseStyles.link.hoverColor !== undefined) {
      const resolvedHoverColor = resolveForScss(baseStyles.link.hoverColor, prefix, tokens, 'colorPalette');
      lines.push('');
      lines.push(':where(a:hover) {');
      lines.push(`  color: ${resolvedHoverColor};`);
      lines.push('}');
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Append CSS declarations for a base style element definition.
 * Handles typography properties (camelCase → kebab-case) and
 * color properties (color → color, background → background-color).
 */
function appendDeclarations(
  lines: string[],
  def: BaseStyleElementDef,
  prefix: string,
  tokens: StbConfig['tokens'],
  indent: string,
): void {
  // Typography declarations
  for (const prop of PROPERTY_ORDER) {
    const value = def[prop];
    if (value === undefined) continue;
    const cssProperty = camelToKebab(prop);
    const resolvedValue = resolveForScss(value, prefix, tokens);
    lines.push(`${indent}${cssProperty}: ${resolvedValue};`);
  }

  // Color declarations
  if (def.color !== undefined) {
    const resolvedValue = resolveForScss(def.color, prefix, tokens, 'colorPalette');
    lines.push(`${indent}color: ${resolvedValue};`);
  }
  if (def.background !== undefined) {
    const resolvedValue = resolveForScss(def.background, prefix, tokens, 'colorPalette');
    lines.push(`${indent}background-color: ${resolvedValue};`);
  }
}

/**
 * Append root padding CSS custom properties inside the body block.
 * Only defined sides are output. Uses 'spacing' as preferred category
 * to resolve ambiguous keys like "large" that exist in both spacing and fontSize.
 */
function appendRootPaddingVars(
  lines: string[],
  padding: BaseStylesSpacingPadding,
  prefix: string,
  tokens: StbConfig['tokens'],
): void {
  for (const side of PADDING_SIDES) {
    const value = padding[side];
    if (value === undefined) continue;
    const resolvedValue = resolveForScss(value, prefix, tokens, 'spacing');
    lines.push(`  --${prefix}--root-padding-${side}: ${resolvedValue};`);
  }
}

/**
 * Append block gap CSS custom property inside the body block.
 * Resolves token references using 'spacing' as preferred category.
 */
function appendBlockGapVar(
  lines: string[],
  spacing: BaseStylesSpacing,
  prefix: string,
  tokens: StbConfig['tokens'],
): void {
  if (!spacing.blockGap) return;
  const resolvedValue = resolveForScss(spacing.blockGap, prefix, tokens, 'spacing');
  lines.push(`  --${prefix}--root-block-gap: ${resolvedValue};`);
}

/**
 * Append layout utility rules that mirror WordPress block gap behavior.
 * Uses the root block gap CSS custom property set in appendBlockGapVar.
 *
 * - Constrained/flow layouts: margin-block-start on children
 * - Flex/grid layouts: gap on the container
 */
function appendBlockGapRules(lines: string[], prefix: string): void {
  lines.push('');
  lines.push(`:where(.is-layout-constrained) > * + * {`);
  lines.push(`  margin-block-start: var(--${prefix}--root-block-gap);`);
  lines.push('}');

  lines.push('');
  lines.push(`:where(.is-layout-flex) {`);
  lines.push(`  gap: var(--${prefix}--root-block-gap);`);
  lines.push('}');

  lines.push('');
  lines.push(`:where(.is-layout-grid) {`);
  lines.push(`  gap: var(--${prefix}--root-block-gap);`);
  lines.push('}');
}
