import type { StbConfig } from '../types.js';

const FORMAT_MAP: Record<string, string> = {
  '.woff2': 'woff2',
  '.woff': 'woff',
  '.ttf': 'truetype',
  '.otf': 'opentype',
};

function inferFormat(filename: string): string {
  const ext = filename.slice(filename.lastIndexOf('.'));
  return FORMAT_MAP[ext] ?? 'woff2';
}

export function generateFontsCss(config: StbConfig): string | null {
  const group = config.tokens.fontFamily;
  if (!group) return null;

  const blocks: string[] = [];

  for (const entry of Object.values(group)) {
    if (!entry.fontFace || !entry.name || !entry.slug) continue;

    for (const face of entry.fontFace) {
      const format = inferFormat(face.src);
      blocks.push(
        `@font-face {\n` +
        `  font-family: '${entry.name}';\n` +
        `  font-style: ${face.style};\n` +
        `  font-weight: ${face.weight};\n` +
        `  src: url('/fonts/${entry.slug}/${face.src}') format('${format}');\n` +
        `}`,
      );
    }
  }

  if (blocks.length === 0) return null;

  return `/* Auto-generated by component2block — do not edit manually */\n\n${blocks.join('\n\n')}\n`;
}
