import type { StbConfig } from '../types.js';
import { CATEGORY_REGISTRY, CATEGORY_ORDER } from '../types.js';
import { buildFluidClamp } from './fluid.js';

export function generateTokensWpCss(config: StbConfig): string {
  const lines: string[] = [
    '/* Auto-generated by component2block — do not edit manually */',
    '',
    ':root {',
  ];

  let firstCategory = true;

  for (const category of CATEGORY_ORDER) {
    const group = config.tokens[category];
    if (!group) continue;

    const def = CATEGORY_REGISTRY[category];

    if (!firstCategory) {
      lines.push('');
    }
    firstCategory = false;

    lines.push(`  /* ${def.label} */`);

    for (const [key, entry] of Object.entries(group)) {
      const varName = `--${config.prefix}--${def.cssSegment}-${key}`;
      const fallback = entry.fluid ? buildFluidClamp(entry) ?? entry.value : entry.value;

      if (def.wpPreset && entry.slug) {
        lines.push(`  ${varName}: var(${def.wpPreset}--${entry.slug}, ${fallback});`);
      } else {
        lines.push(`  ${varName}: ${fallback};`);
      }
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
