import type { StbConfig, BaseStyleElementDef } from '../types.js';
import { camelToKebab } from '../types.js';
import { resolveForScss, ensureFontStyle } from '../config.js';

/** Property output order for consistent generated CSS */
const PROPERTY_ORDER = ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'lineHeight'] as const;

export function generateContentScss(config: StbConfig): string | null {
  if (!config.baseStyles) return null;

  const lines: string[] = [
    '/* Auto-generated by story-to-block — do not edit manually */',
    '',
  ];

  const { baseStyles, prefix, tokens } = config;

  // Body — wraps in body { } to match theme.json styles.typography
  if (baseStyles.body) {
    lines.push('body {');
    appendDeclarations(lines, baseStyles.body, prefix, tokens, '  ');
    lines.push('}');
  }

  // Heading group — :where(h1, h2, h3, h4, h5, h6) { ... }
  if (baseStyles.heading) {
    lines.push('');
    lines.push(':where(h1, h2, h3, h4, h5, h6) {');
    appendDeclarations(lines, baseStyles.heading, prefix, tokens, '  ');
    lines.push('}');
  }

  // Individual headings — :where(hN) { ... }
  const headingLevels = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] as const;
  for (const level of headingLevels) {
    const def = baseStyles[level];
    if (!def) continue;
    lines.push('');
    lines.push(`:where(${level}) {`);
    appendDeclarations(lines, ensureFontStyle(def), prefix, tokens, '  ');
    lines.push('}');
  }

  // Caption — :where(figcaption) { ... }
  if (baseStyles.caption) {
    lines.push('');
    lines.push(':where(figcaption) {');
    appendDeclarations(lines, baseStyles.caption, prefix, tokens, '  ');
    lines.push('}');
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Append CSS declarations for a base style element definition.
 * Converts camelCase properties to kebab-case and resolves token references.
 */
function appendDeclarations(
  lines: string[],
  def: BaseStyleElementDef,
  prefix: string,
  tokens: StbConfig['tokens'],
  indent: string,
): void {
  for (const prop of PROPERTY_ORDER) {
    const value = def[prop];
    if (value === undefined) continue;
    const cssProperty = camelToKebab(prop);
    const resolvedValue = resolveForScss(value, prefix, tokens);
    lines.push(`${indent}${cssProperty}: ${resolvedValue};`);
  }
}
