import type { StbConfig, TokenCategory } from '../types.js';
import { CATEGORY_CSS_SEGMENT, WP_PRESET_MAPPING } from '../types.js';

const CATEGORY_ORDER: TokenCategory[] = [
  'color', 'spacing', 'fontFamily', 'fontSize', 'fontWeight',
  'lineHeight', 'radius', 'shadow', 'transition', 'zIndex',
];

const CATEGORY_LABELS: Record<TokenCategory, string> = {
  color: 'Colors',
  spacing: 'Spacing',
  fontFamily: 'Font Families',
  fontSize: 'Font Sizes',
  fontWeight: 'Font Weights',
  lineHeight: 'Line Heights',
  radius: 'Border Radius',
  shadow: 'Shadows',
  transition: 'Transitions',
  zIndex: 'Z-Index',
};

export function generateTokensWpCss(config: StbConfig): string {
  const lines: string[] = [
    '/* Auto-generated by story-to-block — do not edit manually */',
    '',
    ':root {',
  ];

  let firstCategory = true;

  for (const category of CATEGORY_ORDER) {
    const group = config.tokens[category];
    if (!group) continue;

    if (!firstCategory) {
      lines.push('');
    }
    firstCategory = false;

    lines.push(`  /* ${CATEGORY_LABELS[category]} */`);

    const wpPreset = WP_PRESET_MAPPING[category];

    for (const [key, entry] of Object.entries(group)) {
      const segment = CATEGORY_CSS_SEGMENT[category];
      const varName = `--${config.prefix}-${segment}-${key}`;

      if (wpPreset && entry.slug) {
        lines.push(`  ${varName}: var(${wpPreset}--${entry.slug}, ${entry.value});`);
      } else {
        lines.push(`  ${varName}: ${entry.value};`);
      }
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
