import { describe, it, expect } from 'vitest';
import { generateTokensCss } from '../src/generators/tokens-css.js';
import type { StbConfig } from '../src/types.js';

const config: StbConfig = {
  prefix: 'test',
  tokensPath: 'src/styles/tokens.css',

  outDir: 'dist/wp',
  tokens: {
    colorPalette: {
      primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      'primary-hover': { value: '#005a87' },
    },
    spacing: {
      md: { value: '1rem', slug: '40', name: 'Medium' },
    },
    fontFamily: {
      base: { value: 'sans-serif', name: 'Sans', slug: 'body' },
    },
    fontSize: {
      sm: { value: '0.875rem', slug: 'small', name: 'Small' },
      xs: { value: '0.75rem' },
    },
    zIndex: {
      modal: { value: '300' },
    },
  },
};

describe('generateTokensCss', () => {
  const output = generateTokensCss(config);

  it('includes the auto-generated header', () => {
    expect(output).toContain('Auto-generated by component2block');
  });

  it('generates correct color variables', () => {
    expect(output).toContain('--test--color-primary: #0073aa;');
    expect(output).toContain('--test--color-primary-hover: #005a87;');
  });

  it('generates correct spacing variables', () => {
    expect(output).toContain('--test--spacing-md: 1rem;');
  });

  it('generates correct font-family variables', () => {
    expect(output).toContain('--test--font-family-base: sans-serif;');
  });

  it('generates correct font-size variables', () => {
    expect(output).toContain('--test--font-size-sm: 0.875rem;');
    expect(output).toContain('--test--font-size-xs: 0.75rem;');
  });

  it('generates correct z-index variables', () => {
    expect(output).toContain('--test--z-modal: 300;');
  });

  it('groups tokens by category with comments', () => {
    expect(output).toContain('/* Colors */');
    expect(output).toContain('/* Spacing */');
    expect(output).toContain('/* Z-Index */');
  });

  it('wraps in :root selector', () => {
    expect(output).toContain(':root {');
    expect(output).toContain('}');
  });

  it('uses hardcoded values for all tokens (no var() wrappers)', () => {
    expect(output).not.toContain('var(');
  });
});

describe('generateTokensCss — layout tokens', () => {
  const layoutConfig: StbConfig = {
    prefix: 'test',
    tokensPath: 'src/styles/tokens.css',
    outDir: 'dist/wp',
    tokens: {
      layout: {
        'content-size': { value: '645px' },
        'wide-size': { value: '1340px' },
      },
    },
  };

  const output = generateTokensCss(layoutConfig);

  it('generates layout CSS variables', () => {
    expect(output).toContain('--test--layout-content-size: 645px;');
    expect(output).toContain('--test--layout-wide-size: 1340px;');
  });

  it('groups layout tokens with a comment', () => {
    expect(output).toContain('/* Layout */');
  });
});

describe('generateTokensCss — fluid font sizes', () => {
  const fluidConfig: StbConfig = {
    prefix: 'test',
    tokensPath: 'src/styles/tokens.css',
    outDir: 'dist/wp',
    tokens: {
      fontSize: {
        medium: {
          value: '1.125rem',
          slug: 'medium',
          name: 'Medium',
          fluid: { min: '0.875rem', max: '1.125rem' },
        },
        large: {
          value: '1.75rem',
          slug: 'large',
          name: 'Large',
          fluid: { min: '1.25rem', max: '1.75rem' },
        },
        static: {
          value: '0.75rem',
          slug: 'static',
          name: 'Static',
        },
      },
    },
  };

  const output = generateTokensCss(fluidConfig);

  it('generates clamp() for fluid font sizes', () => {
    expect(output).toContain(
      '--test--font-size-medium: clamp(0.875rem, 0.875rem + ((0.25) * ((100vw - 320px) / 1280)), 1.125rem);'
    );
  });

  it('uses correct range for larger fluid sizes', () => {
    expect(output).toContain(
      '--test--font-size-large: clamp(1.25rem, 1.25rem + ((0.5) * ((100vw - 320px) / 1280)), 1.75rem);'
    );
  });

  it('uses static value when no fluid is defined', () => {
    expect(output).toContain('--test--font-size-static: 0.75rem;');
  });
});
