import { describe, it, expect } from 'vitest';
import { generateContentScss } from '../src/generators/content-scss.js';
import type { StbConfig } from '../src/types.js';

const config: StbConfig = {
  prefix: 'design-system',
  tokensPath: 'src/styles/tokens.css',
  outDir: 'dist/wp',
  wpThemeable: false,
  tokens: {
    fontFamily: {
      inter: { value: 'Inter, sans-serif', name: 'Inter', slug: 'inter' },
    },
    fontSize: {
      small: { value: '1rem', name: 'Small', slug: 'small' },
      medium: { value: '1.125rem', name: 'Medium', slug: 'medium' },
    },
  },
  baseStyles: {
    body: {
      fontFamily: 'inter',
      fontSize: 'medium',
      fontWeight: '400',
      lineHeight: '1.6',
    },
    heading: {
      fontFamily: 'inter',
    },
    h1: { fontSize: '4.5rem', fontWeight: '500' },
    h2: { fontSize: '3rem', fontWeight: '500' },
    h6: { fontSize: '1.45rem', fontWeight: '500', fontStyle: 'italic' },
    caption: { fontSize: 'small', fontStyle: 'italic', fontWeight: '300' },
  },
};

describe('generateContentScss', () => {
  it('returns null when no baseStyles', () => {
    const result = generateContentScss({ ...config, baseStyles: undefined });
    expect(result).toBeNull();
  });

  it('includes auto-generated header', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('Auto-generated by story-to-block');
  });

  it('body declarations are wrapped in body selector', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('body {');
    const bodyBlock = result.split('body {')[1].split('}')[0];
    expect(bodyBlock).toContain('font-family:');
  });

  it('body resolves token references to CSS variables', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('  font-family: var(--design-system--font-family-inter);');
    expect(result).toContain('  font-size: var(--design-system--font-size-medium);');
  });

  it('body passes raw values through unchanged', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain('  font-weight: 400;');
    expect(result).toContain('  line-height: 1.6;');
  });

  it('heading group uses :where(h1, h2, h3, h4, h5, h6) selector', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain(':where(h1, h2, h3, h4, h5, h6) {');
    expect(result).toContain('  font-family: var(--design-system--font-family-inter);');
  });

  it('individual headings use :where(hN) selectors', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain(':where(h1) {');
    expect(result).toContain(':where(h2) {');
  });

  it('individual headings include font-style: normal by default', () => {
    const result = generateContentScss(config)!;
    // h1 has no fontStyle in config — should get normal
    const h1Block = result.split(':where(h1) {')[1].split('}')[0];
    expect(h1Block).toContain('font-style: normal;');
  });

  it('explicit fontStyle overrides the normal default', () => {
    const result = generateContentScss(config)!;
    // h6 has fontStyle: 'italic' in config
    const h6Block = result.split(':where(h6) {')[1].split('}')[0];
    expect(h6Block).toContain('font-style: italic;');
    expect(h6Block).not.toContain('font-style: normal;');
  });

  it('caption maps to :where(figcaption) selector', () => {
    const result = generateContentScss(config)!;
    expect(result).toContain(':where(figcaption) {');
  });

  it('caption resolves token references', () => {
    const result = generateContentScss(config)!;
    const captionBlock = result.split(':where(figcaption) {')[1].split('}')[0];
    expect(captionBlock).toContain('font-size: var(--design-system--font-size-small);');
  });

  it('outputs properties in consistent order', () => {
    const result = generateContentScss(config)!;
    // In body: fontFamily before fontSize before fontWeight before lineHeight
    const fontFamilyIdx = result.indexOf('  font-family: var(--design-system--font-family-inter);');
    const fontSizeIdx = result.indexOf('  font-size: var(--design-system--font-size-medium);');
    const fontWeightIdx = result.indexOf('  font-weight: 400;');
    const lineHeightIdx = result.indexOf('  line-height: 1.6;');
    expect(fontFamilyIdx).toBeLessThan(fontSizeIdx);
    expect(fontSizeIdx).toBeLessThan(fontWeightIdx);
    expect(fontWeightIdx).toBeLessThan(lineHeightIdx);
  });
});
