import { describe, it, expect } from 'vitest';
import { generateTokensCss } from '../src/generators/tokens-css.js';
import type { StbConfig } from '../src/types.js';

const config: StbConfig = {
  prefix: 'test',
  tokensPath: 'src/styles/tokens.css',
  outDir: 'dist/wp',
  tokens: {
    color: {
      primary: { value: '#0073aa', name: 'Primary', slug: 'primary' },
      'primary-hover': { value: '#005a87' },
    },
    spacing: {
      md: { value: '1rem', slug: '40', name: 'Medium' },
    },
    fontFamily: {
      base: { value: 'sans-serif', name: 'Sans', slug: 'body' },
    },
    fontSize: {
      sm: { value: '0.875rem', slug: 'small', name: 'Small' },
      xs: { value: '0.75rem' },
    },
    zIndex: {
      modal: { value: '300' },
    },
  },
};

describe('generateTokensCss', () => {
  const output = generateTokensCss(config);

  it('includes the auto-generated header', () => {
    expect(output).toContain('Auto-generated by story-to-block');
  });

  it('generates correct color variables', () => {
    expect(output).toContain('--test-color-primary: #0073aa;');
    expect(output).toContain('--test-color-primary-hover: #005a87;');
  });

  it('generates correct spacing variables', () => {
    expect(output).toContain('--test-spacing-md: 1rem;');
  });

  it('generates correct font-family variables', () => {
    expect(output).toContain('--test-font-family-base: sans-serif;');
  });

  it('generates correct font-size variables', () => {
    expect(output).toContain('--test-font-size-sm: 0.875rem;');
    expect(output).toContain('--test-font-size-xs: 0.75rem;');
  });

  it('generates correct z-index variables', () => {
    expect(output).toContain('--test-z-modal: 300;');
  });

  it('groups tokens by category with comments', () => {
    expect(output).toContain('/* Colors */');
    expect(output).toContain('/* Spacing */');
    expect(output).toContain('/* Z-Index */');
  });

  it('wraps in :root selector', () => {
    expect(output).toContain(':root {');
    expect(output).toContain('}');
  });

  it('uses hardcoded values for all tokens (no var() wrappers)', () => {
    expect(output).not.toContain('var(');
  });
});
